spring:
  application:
    name: parc-prehistorique
  datasource:
    url: jdbc:postgresql://localhost:5432/parc_prehistorique
    username: postgres
    password: azerty+35
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true